### ISSUE TITLE
README documentation suggestion - Username should be in domain\username

### ISSUE THREAD

**Issue by curious-bryan** [mikaelene/dbt-sqlserver#1]
@mikaelene sweet adapter!  Thank you for this contribution!  

When I first tried to connect with `dbt debug`, I could not connect until I my username was in the `domain\username` format.  At first, I was expecting `username` or `username@domain.com` format.  I didn't think to use `domain\username` format until reading some documentation on `pymssql` ([link](http://www.pymssql.org/en/stable/pymssql_examples.html#connecting-using-windows-authentication)), 

Not sure if anyone else needs the hint or if the situation is specific to my set up.  But if you think it is helpful, perhaps something similar to 
following would nudge users in the right direction.

### Configure your profile
```
  type: sqlserver
  ...
  user: domain\username
  ...
```

**Comment by mikaelene** [comment]
Hi! 

I have only implemented and tested the SQL user approach for connecting to sql server. Like user:sa pass:password. There you don’t need domain. 

Are you connecting with domainuser. Like AD user? In that case, maybe I should add Intergrated security mode?

I’ll have a look! 😀

**Comment by mikaelene** [comment]
Updated readme

**Comment by curious-bryan** [comment]
@mikaelene, yep.  I connected with domainuser from AD.  I tried SA, but no dice.  I might have mistyped something though.
