### ISSUE TITLE
Make dbt_utils and surrogate_key() work

### ISSUE THREAD

**Issue by KimchaC** [mikaelene/dbt-sqlserver#10]
After installing the adapter most of the dbt_utils functions didn't work. I falsely assumed that it's because this adapter didn't implement all the required functionality, but after reading [this dbt issue](https://github.com/fishtown-analytics/dbt/issues/1457) I understood it's not related to this adapter at all.

While the dbt team works on a solution for this I wanted to document my workaround here.

Add to `dbt_modules/dbt_utils/macros/custom/sqlserver_adapters.sql`:
```
{% macro sqlserver__type_string() %}
    varchar
{% endmacro %}

{% macro sqlserver__concat(fields) -%}
    concat({{ fields|join(', ') }}, '')
{%- endmacro %}

{% macro sqlserver__hash(field) -%}
    hashbytes('md5', {{field}})
{%- endmacro %}
```

Add `dbt_modules/.gitignore`:
```
*
!*/
!dbt_utils/macros/custom/**
```

**Comment by mikaelene** [comment]
Hi, 

I've noticed this to. I have another project that implements most of the dbt-utils macros: [dbt-utils-sqlserver](https://github.com/mikaelene/dbt-utils-sqlserver). But it was quite a fast hack and can probably be implemented much better.

Your workaround seems good!

**Comment by KimchaC** [comment]
Ah that’s even better! Thanks for all the effort. 

Perhaps you can add it to the readme so that other users can find it easier.
