### ISSUE TITLE
dbt source snapshot-freshness UTC ?

### ISSUE THREAD

**Issue by pgodwin** [mikaelene/dbt-sqlserver#17]
Not entirely sure if this is a dbt issue or dbt-sqlserver. 

When using the 'freshness' support in dbt and calling `dbt source snapshot-freshness`, it seems to comparing to local time rather than UTC time. 

Any ideas? Or is this performed internally in dbt?

**Comment by mikaelene** [comment]
I am almost sure this is handled in dbt core. Closing but feel free to open if I am wrong.
