### ISSUE TITLE
Interpolate values in log lines

### ISSUE THREAD

**Issue by drewbanin** [mikaelene/dbt-sqlserver#19]
I'm seeing some issues where the logs in `logs/dbt.log` are missing some crucial information that would help with debugging.

Check out this example:
https://github.com/mikaelene/dbt-sqlserver/blob/fb228938805289b1ba84bf21534730d3e8d5a63c/dbt/adapters/sqlserver/connections.py#L144-L146

I think this code should instead read:
```
    logger.debug('On {}: {}....', connection.name, sql[0:512])
else:
    logger.debug('On {}: {}', connection.name, sql)
```

Changing the `%s` fields to `{}` will get the logger to correctly interpolate log values as shown [here](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/core/dbt/adapters/sql/connections.py#L66-L70)

I'd be happy to make a PR for this change :)

**Comment by joncooper** [comment]
Hm, Python's `logging` package using its own flavor of interpolation that is different than previous `%` style or `f-strings` is confusing!

https://stackoverflow.com/questions/34619790/pylint-message-logging-format-interpolation

**Comment by mikaelene** [comment]
Thanks! Pull request would be most welcome :-)
