### ISSUE TITLE
dbt.log not showing the sql code being executed

### ISSUE THREAD

**Issue by puruzio** [mikaelene/dbt-sqlserver#22]
I'm not sure if there is a way to configure dbt or dbt-sqlserver to show the sql code being executed in the log.

Otherwise, it will be really nice if there is a way to see it for debugging and better understanding of what's happening under the hood.

For instance, one of my incrementally materialized models has `unique_key='...'` option turned on. Being able to see the exact delete and insert statement will help understand what's being done.

Thank you!

**Comment by mikaelene** [comment]
I think this is a cause of issue #19 . Feel free to reopen if it's not fixed after that issue is solved.
