### ISSUE TITLE
Incompatible with  dbt>0.15, should update setup.py

### ISSUE THREAD

**Issue by alittlesliceoftom** [mikaelene/dbt-sqlserver#31]
Reference [issue ](https://github.com/fishtown-analytics/dbt/issues/2423) describes incorrect duplicate macros when using dbt>0.15 with dbt-sqlserver=0.15.

" One helpful change might be for the maintainer of dbt-sqlserver to change their requirements for the package from >=0.15.0 to something like >=0.15.0, <0.16."

**Comment by swanderz** [comment]
@alittlesliceoftom agreed. Can you make the PR? I'm happy to if you can't.

**Comment by alittlesliceoftom** [comment]
Can do

**Comment by mikaelene** [comment]
This is a great feature. I’ll approve any PR on this
