### ISSUE TITLE
Schema tests raise SQL error when columns contain space

### ISSUE THREAD

**Issue by camfrout** [mikaelene/dbt-sqlserver#37]
Hi,

Schema tests on columns that contain spaces are currently raising a SQL error. This is due to the macro generating the following SQL code
```
select count(*) as validation_errors
from "DB"."schema"."table"
where My Column Name is null
```

I tried to change the column name in `schema.yml` to put it in the format `"'My Column Name'"`, but while the schema test now works, the documentation shows 2 different entries for my column, one with `My Column Name` and one with `'My Column Name'` (including the single quotes).

I also tried to replace `My Column Name` with `[My Column Name]` but I get the same result, the test is working but I am getting a duplicate column in the documentation.

I think that wrapping the column name in single quotes in the macros defined in [schema_tests.sql](https://github.com/mikaelene/dbt-sqlserver/blob/master/dbt/include/sqlserver/macros/schema_tests.sql) would prevent this problem. So, replacing `{% set column_name = kwargs.get('column_name', kwargs.get('arg')) %}` by `{% set column_name = "'" ~ kwargs.get('column_name', kwargs.get('arg')) ~ "'" %}`

Does it sound ok? If so, I am happy to create a Pull Request with those changes.

**Comment by mikaelene** [comment]
Hi! That sounds ok. I know there is a setting somewhere around quoting policies. I don’t know if that would be picked up by the adapter, but maybe worth a try?

**Comment by swanderz** [comment]
Isn't this a good scenario for using `adapter.quote()`? I'm out of my depth here, but it looks like it isn't a macro, but an attribute of the adapter class?

I see a few example where `adapter.quote()` is used in this adapter. Perhaps the solution is to more widely adopt using this approach? Assuming we can properly set the quoting...

**Comment by camfrout** [comment]
The `adapter.quote()` approach works fine and is using `"` quotations in my case.

If we want to follow the approach taken in [this dbt issue](https://github.com/fishtown-analytics/dbt/pull/925) we can actually replace `kwargs.get('column_name', kwargs.get('arg'))` by `adapter.quote_as_configured(kwargs.get('column_name', kwargs.get('arg')),'identifier')` and we will then be following the quoting policy of the dbt project.

Happy to submit a PR with `adapter.quote_as_configured` if it makes sense to you.

**Comment by camfrout** [comment]
This might actually just be slightly more complex. 
The problem with the approaches above is that it breaks the ability to use SQL expressions in the schema tests.

For example, my test on `CONCAT(col1,col2)` that needs to be unique in my model is not working anymore if I add quotes around `kwargs.get('column_name', kwargs.get('arg'))`. The macro compiles as `select
        "CONCAT(col1,col2)" as validation_errors ...` which of course is not correct. This same test works if I don't use the new quotes.

**Comment by swanderz** [comment]
@camfrout you want to try the #46 out and see if it fixes the quoting issue you're having?

**Comment by camfrout** [comment]
I just tried to use the `quote` column property along with #46 and the tests work fine, even with columns with spaces. So I will close this one and there is no need to update `schema_tests.sql`.
