### ISSUE TITLE
DB-Lib error message 20002

### ISSUE THREAD

**Issue by tomdavidson** [mikaelene/dbt-sqlserver#4]
Hello and thank you for this contrib.

My `dbt debug` fails on the connection test:

```
 >Database Error
  (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (jaffle-shop-warehouse.database.windows.net:1433)\n')
```

dbt-sqlserver          0.1.4.1
dbt                         0.14.0 
pymssql                  2.1.4 | 2.13
python                    3.6.8 | 2.7.15

The database is an Azure SQL DB. I have the correct firewall settings all the way around and can connect to the db with the Azure query editor.

**Comment by mikaelene** [comment]
Hey! The adapter should work with azure sql dB but I haven’t tried really. I am thinking about switching to pyodbc as people apparently prefer that. Maybe that will solve the problem. As a first step you can try http://pymssql.org/en/stable/azure.html

**Comment by KimchaC** [comment]
I think this issue may be related to this:
https://github.com/mikaelene/dbt-sqlserver/issues/9
