### ISSUE TITLE
Snapshot Second Run Problem

### ISSUE THREAD

**Issue by kofoide** [mikaelene/dbt-sqlserver#40]
I am having a problem with running a snapshot after the initial snapshot table is created (running dbt snapshot for the second time)

I am pretty new to dbt, so I could have some sort of configuration problem too, but I am able to materialize other objects.

I have SQL Server profile trace running to capture the activity and it seems that it is creating a temp table, then it drops the temp table, then it tries to use the temp table to do the merge into the snapshot.

I am attaching the trace results so you can exactly what is happening on my server.

[trace.trc.zip](https://github.com/mikaelene/dbt-sqlserver/files/4990347/trace.trc.zip)

**Comment by mikaelene** [comment]
There is a limitation in dbt-sqlserver that the table/query you are basing the snapshot on can’t have any constraints. Such as columns with not null setttings etc. That is usually the case for failing second run. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kofoide** [comment]
I am very new to submitting pull request changes to someone else's repo, but I am going to give it a try. I believe I found the source of this issue and was able to fix it. This brought me to another issue that I was able to fix as well. I hope I am doing this the right way.
