### ISSUE TITLE
Bring in AAD auth from dbt-synapse?

### ISSUE THREAD

**Issue by swanderz** [mikaelene/dbt-sqlserver#45]
@josephcdonaldson mentioned they'd like AAD auth available as part of `dbt-sqlserver`. Perhaps I open a PR to try and merge our `connections.py`?

**Comment by mikaelene** [comment]
That would be great as long as the other auths work. Merge it in 0.18 if you find that it works. I’ll try to release it when dbt 0.18 is out.

**Comment by swanderz** [comment]
We just realized we're missing one key AAD auth method, service principal. We'll aim to have a PR in by the end of the week with the 3 supported AAD methods plus service principal by the end of the week.

**Comment by mikaelene** [comment]
This is solved by PR #53 and #55
