### ISSUE TITLE
Refactor the create table as macros

### ISSUE THREAD

**Issue by mikaelene** [mikaelene/dbt-sqlserver#6]
The macro for creating a table for a model ([sqlserver__create_table_as](https://github.com/mikaelene/dbt-sqlserver/blob/9db85291aad9e80a441e5d453269eafe9a9b2889/dbt/include/sqlserver/macros/adapters.sql#L72)) is quite complicated and in case of error leaves unfinished models in the database. The next run might get an error in case the temp-view already exists etc.

The macro should be splitt up in different parts and maybe utilize the [sqlserver__create_view_as](https://github.com/mikaelene/dbt-sqlserver/blob/9db85291aad9e80a441e5d453269eafe9a9b2889/dbt/include/sqlserver/macros/adapters.sql#L56) macro instead of encapsulating a run EXEC() command. Or is there a dbt-macro that also drops the temp_view if it already exists?

**Comment by dubravcik** [comment]
Hi, @mikaelene , let's blame SQL Server for such bad syntax to create table as select :-/ Anyway, I prepared a function to alter the original SQL script and insert the "INTO" statement. It works for all my sql scripts but further testing will be needed. What it does is to find the correct FROM statement (one when parentheses counter is equal zero).

Could you help - where can I insert the code to be able to call from jinja? Thanks
```    
def insert_into(sql, table_name):
        parentheses_count = 0
        index = 0
        into_index = 0
        for char in string:
            index += 1
            if char == "(":
                parentheses_count += 1
            elif char == ")":
                parentheses_count -= 1
            if parentheses_count == 0 and string[index:index+4:] == "FROM":
                into_index = index    
        return string[:into_index] + " INTO  "+ table_name +" " + string[into_index:]
```

**Comment by mikaelene** [comment]
Thanks @dubravcik ! 

I actually don't know where to put this. Jinja is a language of its own and i don't think you can put Python in to it. Maybe the guys at Fishtown analytics knows how to utilise it.

**Comment by dubravcik** [comment]
I found it out .. it has to be adapter method.. but I am unable to push to this repo. So I am adding it here:

impl.py
```
from dbt.adapters.base.meta import available

    @available
    def insert_into(cls, sql, schema, identifier):
        parentheses_count = 0
        index = 0
        into_index = len(sql)
        for char in sql:
            index += 1
            if char == "(":
                parentheses_count += 1
            elif char == ")":
                parentheses_count -= 1
            if parentheses_count == 0 and sql[index:index+4:] == "FROM":
                into_index = index    
        return sql[:into_index] + " INTO  "+ schema+"."+identifier +" " + sql[into_index:]
```
adapters.sql
```
{% macro sqlserver__create_table_as(temporary, relation, sql) -%}
   {%- set as_columnstore = config.get('as_columnstore', default=true) -%}

   {{ adapter.insert_into(sql, relation.schema, relation.identifier) }} ;
    
   {% if not temporary and as_columnstore -%}
    DROP INDEX IF EXISTS {{ relation.schema }}.{{ relation.identifier }}.{{ relation.schema }}_{{ relation.identifier }}_cci
    CREATE CLUSTERED COLUMNSTORE INDEX {{ relation.schema }}_{{ relation.identifier }}_cci
    ON {{ relation.schema }}.{{ relation.identifier }}
   {% endif %}
{% endmacro %}
```

**Comment by mikaelene** [comment]
Great work! Can you create a branch and sublit a pull request? I also wonders what will happen if a column is named i.e. FROM_DATE. Will the macro work that out?

**Comment by dubravcik** [comment]
You hit it, it wouldn't work, event comments containg "from" will break it. So this implementation is not good and it requires regular SQL parser to work properly.

**Comment by mikaelene** [comment]
Closed with https://github.com/mikaelene/dbt-sqlserver/commit/7ba26bf70c3c201d9aa1f0567aa3592893be0678
